set(CMAKE_C_COMPILER ${PGO_STAGE_1_INSTALL_PATH}/bin/clang CACHE STRING "")
set(CMAKE_CXX_COMPILER ${PGO_STAGE_1_INSTALL_PATH}/bin/clang++ CACHE STRING "")
set(CMAKE_BUILD_TYPE RELEASE CACHE STRING "")
set(CLANG_ENABLE_BOOTSTRAP ON CACHE BOOL "")

set(CMAKE_INSTALL_PREFIX ${PGO_STAGE_3_INSTALL_PATH} CACHE STRING "")

set(LLVM_ENABLE_PROJECTS clang;clang-tools-extra;compiler-rt;llvm CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES compiler-rt;libcxx;libcxxabi CACHE STRING "")
set(LLVM_BUILD_EXTERNAL_COMPILER_RT ON CACHE BOOL "")

set(LLVM_TARGETS_TO_BUILD Native CACHE STRING "")
set(PGO_INSTRUMENT_LTO ON CACHE BOOL "")

# Set your profile data path here
set(LLVM_PROFDATA_FILE /path/to/output/profdata.prof CACHE STRING "")
