set(PGO_STAGE_1_INSTALL_PATH /scratch/eopc/PGO/stage_1_install CACHE STRING "")

set(CMAKE_C_COMPILER gcc CACHE STRING "")
set(CMAKE_CXX_COMPILER g++ CACHE STRING "")
set(CMAKE_BUILD_TYPE RELEASE CACHE STRING "")

set(CMAKE_INSTALL_PREFIX ${PGO_STAGE_1_INSTALL_PATH} CACHE STRING "")

set(LLVM_TARGETS_TO_BUILD Native CACHE STRING "")
set(LLVM_ENABLE_PROJECTS clang;clang-tools-extra;compiler-rt;llvm CACHE STRING "")
set(LLVM_BUILD_EXTERNAL_COMPILER_RT ON CACHE BOOL "")

set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(LLVM_CCACHE_BUILD ON CACHE BOOL "")
set(LLVM_ENABLE_ASSERTIONS ON CACHE BOOL "")
